openapi: 3.0.0
info:
  title: Car Wash Booking API
  description: API for booking car wash services
  version: 1.0.0
servers:
  - url: http://localhost:8000
paths:
  /v1/api/bookings:
    post:
      summary: Create a new car wash booking
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookingRq'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookingRs'
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
  /v1/api/available-slots:
    get:
      summary: Get available slots for car wash
      parameters:
        - name: date
          in: query
          required: true
          schema:
            type: string
            format: date
            example: "2024-05-01"
            description: Date for which slots are requested
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AvailableSlotsRs'
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
components:
  schemas:
    BookingRq:
      title: BookingRq
      type: object
      properties:
        date:
          type: string
          format: date
          example: "2024-05-01"
          description: Date of the booking
        time:
          type: string
          format: time
          example: "10:00"
          description: Time of the booking
        userId:
          type: string
          example: "123456"
          description: ID of the user making the booking
        serviceType:
          type: string
          enum: [ standard, premium ]
          example: "standard"
          description: Type of car wash service (standard or premium)
    BookingRs:
      type: object
      title: BookingRs
      properties:
        booking_id:
          type: string
          example: "789012"
          description: ID of the newly created booking
    AvailableSlotsRs:
      title: AvailableSlotsRs
      properties:
        availableSlots:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
                example: 1
                description: ID of the branch
              name:
                type: string
                example: "Шаболовская"
                description: Name of the branch
              address:
                type: string
                example: "115419, г.Москва, ул.2-й Верхний Михайловский проезд, д. 9, стр. 2"
                description: Address of the branch
              phone:
                type: string
                example: "+7 (495) 777-88-99"
                description: Phone number of the branch
              filialId:
                type: string
                example: "59fb036d4ccd782ac6458487"
                description: ID of the branch
              workHours:
                type: string
                example: "Ежедневно с 8:00 до 22:00"
                description: Working hours of the branch
              slots:
                type: array
                items:
                  type: string
                  example: "09:00"
                  description: Available time slot